const{$,downloadBlob,drawWave,renderAudio,encodeAudioRealtime,fileExt}=Blue;let file,buffer,ctx,source;const drop=$('#drop');
['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>load(e.dataTransfer.files[0]));$('#file').onchange=e=>load(e.target.files[0]);
async function load(f){if(!f)return;file=f;$('#status').textContent=`Reading ${f.name}…`;try{const C=window.AudioContext||window.webkitAudioContext;ctx=ctx||new C();await ctx.resume();const arr=await f.arrayBuffer();buffer=await ctx.decodeAudioData(arr.slice(0));$('#audioMeta').textContent=`${f.name} • ${buffer.duration.toFixed(2)}s • ${buffer.sampleRate} Hz • ${buffer.numberOfChannels} ch`;drop.style.display='none';$('#track').style.display='block';$('#export').disabled=false;$('#play').disabled=false;$('#replaceAudio').style.display='inline-flex';$('#status').textContent='Real audio decoded and ready to edit.';sync()}catch(e){console.error(e);$('#status').textContent=`Could not decode ${fileExt(f.name).toUpperCase()||'this'} audio on this browser. The file was selected correctly, but Safari/Chrome does not expose a decoder for that codec.`}}
$('#replaceAudio').onclick=()=>$('#file').click();
function vals(){let s=+$('#start').value/1000*buffer.duration,e=+$('#end').value/1000*buffer.duration;if(e<s+.05)e=Math.min(buffer.duration,s+.05);return{s,e}}
function opts(){const{s,e}=vals();return{start:s,end:e,gain:+$('#gain').value/100,fadeIn:+$('#fadeIn').value,fadeOut:+$('#fadeOut').value,normalize:$('#normalize').checked,reverse:$('#reverse').checked}}
function sync(){if(!buffer)return;const{s,e}=vals();$('#rangeLabel').textContent=`${s.toFixed(2)}s – ${e.toFixed(2)}s`;$('#gainVal').textContent=`${$('#gain').value}%`;drawWave($('#wave'),buffer,s,e)}['#start','#end','#gain','#fadeIn','#fadeOut','#normalize','#reverse'].forEach(id=>$(id).addEventListener('input',sync));window.addEventListener('resize',sync);
$('#play').onclick=async()=>{if(!buffer)return;if(source){try{source.stop()}catch{}source=null;$('#play').textContent='▶ Play selection';return}$('#status').textContent='Rendering preview…';const rendered=await renderAudio(buffer,opts());source=ctx.createBufferSource();source.buffer=rendered;source.connect(ctx.destination);source.onended=()=>{source=null;$('#play').textContent='▶ Play selection';$('#status').textContent='Preview finished.'};source.start();$('#play').textContent='■ Stop';$('#status').textContent='Playing the actual edited audio.'};
$('#export').onclick=async()=>{if(!buffer)return;const format=$('#format').value,status=$('#status'),name=file.name.replace(/\.[^.]+$/,'')||'edited';try{status.textContent='Rendering edits from the decoded audio…';const rendered=await renderAudio(buffer,opts());const out=await encodeAudioRealtime(rendered,format,t=>status.textContent=t);downloadBlob(out,`${name}-edited.${format}`);status.textContent=`Exported ${format.toUpperCase()} successfully.`}catch(e){status.textContent=e.message||'Export failed.'}};
