const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const appState={deferredInstall:null};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();appState.deferredInstall=e;});
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function openInstall(){
 const m=$('#installModal'); if(!m)return;
 const body=$('#installText');
 if(isStandalone()) body.innerHTML='<p>Blue Media Studio is already running as an installed app.</p>';
 else if(appState.deferredInstall) body.innerHTML='<p>Your browser can install this app now. Tap <b>Install App</b> below.</p>';
 else if(isIOS()) body.innerHTML='<p>On iPhone/iPad: tap the <b>Share</b> button in Safari, scroll down, then choose <b>Add to Home Screen</b>.</p>';
 else body.innerHTML='<p>Open your browser menu and choose <b>Install app</b> or <b>Add to Home screen</b>. Installation availability depends on the browser.</p>';
 m.classList.add('show');
}
async function doInstall(){if(appState.deferredInstall){appState.deferredInstall.prompt();await appState.deferredInstall.userChoice;appState.deferredInstall=null;$('#installModal')?.classList.remove('show')}else if(isIOS()){alert('In Safari, tap Share → Add to Home Screen.')}}
window.openInstall=openInstall;window.doInstall=doInstall;
window.addEventListener('DOMContentLoaded',()=>{$('#installModal')?.addEventListener('click',e=>{if(e.target.id==='installModal')e.currentTarget.classList.remove('show')});$('#closeInstall')?.addEventListener('click',()=>$('#installModal').classList.remove('show'));$('#installNow')?.addEventListener('click',doInstall);});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
function fmtTime(s){if(!isFinite(s))return'00:00.0';const m=Math.floor(s/60),r=s-m*60;return `${String(m).padStart(2,'0')}:${r.toFixed(1).padStart(4,'0')}`}
function humanBytes(n){if(!n)return'0 B';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200)}
function audioBufferToWav(buffer,start=0,end=buffer.duration,opts={}){const sr=buffer.sampleRate,channels=buffer.numberOfChannels;let s=Math.max(0,Math.floor(start*sr)),e=Math.min(buffer.length,Math.floor(end*sr));if(e<=s)e=buffer.length;const frames=e-s;const out=new ArrayBuffer(44+frames*channels*2);const v=new DataView(out);const w=(o,t)=>[...t].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+frames*channels*2,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels,true);v.setUint32(24,sr,true);v.setUint32(28,sr*channels*2,true);v.setUint16(32,channels*2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,frames*channels*2,true);let off=44;let peak=0;if(opts.normalize){for(let c=0;c<channels;c++){const d=buffer.getChannelData(c);for(let i=s;i<e;i++)peak=Math.max(peak,Math.abs(d[i]))}}const norm=opts.normalize&&peak>0?Math.min(1,0.98/peak):1;const gain=(opts.gain??1)*norm;const fadeIn=Math.max(0,Math.floor((opts.fadeIn||0)*sr)),fadeOut=Math.max(0,Math.floor((opts.fadeOut||0)*sr));for(let i=0;i<frames;i++){let env=1;if(fadeIn&&i<fadeIn)env=i/fadeIn;if(fadeOut&&i>frames-fadeOut)env=Math.min(env,(frames-i)/fadeOut);for(let c=0;c<channels;c++){const d=buffer.getChannelData(c);let sample=d[opts.reverse?(e-1-i):(s+i)]*gain*env;sample=Math.max(-1,Math.min(1,sample));v.setInt16(off,sample<0?sample*0x8000:sample*0x7fff,true);off+=2}}return new Blob([out],{type:'audio/wav'})}
function drawWave(canvas,buffer,selStart=0,selEnd=buffer?.duration||1){if(!canvas||!buffer)return;const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);c.fillStyle='#061021';c.fillRect(0,0,w,h);const data=buffer.getChannelData(0),step=Math.max(1,Math.floor(data.length/w));c.strokeStyle='#3aa7ff';c.lineWidth=1;c.beginPath();for(let x=0;x<w;x++){let min=1,max=-1;const st=x*step;for(let j=0;j<step&&st+j<data.length;j++){const v=data[st+j];if(v<min)min=v;if(v>max)max=v}const y1=(1+min)*h/2,y2=(1+max)*h/2;c.moveTo(x,y1);c.lineTo(x,y2)}c.stroke();const sx=(selStart/buffer.duration)*w,ex=(selEnd/buffer.duration)*w;c.fillStyle='rgba(36,140,255,.12)';c.fillRect(sx,0,Math.max(1,ex-sx),h);c.strokeStyle='#7fd7ff';c.lineWidth=2;c.beginPath();c.moveTo(sx,0);c.lineTo(sx,h);c.moveTo(ex,0);c.lineTo(ex,h);c.stroke()}
async function loadFFmpeg(setStatus=()=>{}){if(window.__ffmpeg)return window.__ffmpeg;setStatus('Loading conversion engine…');const [{FFmpeg},{toBlobURL,fetchFile}]=await Promise.all([import('https://esm.sh/@ffmpeg/ffmpeg@0.12.15'),import('https://esm.sh/@ffmpeg/util@0.12.2')]);const ffmpeg=new FFmpeg();const base='https://unpkg.com/@ffmpeg/core@0.12.10/dist/esm';await ffmpeg.load({coreURL:await toBlobURL(`${base}/ffmpeg-core.js`,'text/javascript'),wasmURL:await toBlobURL(`${base}/ffmpeg-core.wasm`,'application/wasm')});window.__ffmpeg={ffmpeg,fetchFile};setStatus('Conversion engine ready');return window.__ffmpeg}
async function convertWithFFmpeg(file,format,setStatus=()=>{},extra=[]){const {ffmpeg,fetchFile}=await loadFFmpeg(setStatus);const stamp=Date.now();const ext=(file.name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'');const input=`in-${stamp}.${ext}`,output=`out-${stamp}.${format}`;await ffmpeg.writeFile(input,await fetchFile(file));setStatus(`Converting to ${format.toUpperCase()}…`);await ffmpeg.exec(['-i',input,...extra,output]);const data=await ffmpeg.readFile(output);await Promise.allSettled([ffmpeg.deleteFile(input),ffmpeg.deleteFile(output)]);const types={mp3:'audio/mpeg',m4a:'audio/mp4',aac:'audio/aac',flac:'audio/flac',ogg:'audio/ogg',opus:'audio/ogg',wav:'audio/wav',webm:'audio/webm',mp4:'video/mp4',mov:'video/quicktime',gif:'image/gif'};return new Blob([data.buffer],{type:types[format]||'application/octet-stream'})}
window.Blue={$, $$,fmtTime,humanBytes,downloadBlob,audioBufferToWav,drawWave,loadFFmpeg,convertWithFFmpeg};
