const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const appState={deferredInstall:null};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();appState.deferredInstall=e;});
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function openInstall(){const m=$('#installModal');if(!m)return;const body=$('#installText');if(isStandalone())body.innerHTML='<p>Blue Media Studio is already installed.</p>';else if(appState.deferredInstall)body.innerHTML='<p>This browser can install Blue Media Studio now.</p>';else if(isIOS())body.innerHTML='<p>On iPhone/iPad Safari: tap <b>Share</b> → <b>Add to Home Screen</b>.</p>';else body.innerHTML='<p>Open your browser menu and choose <b>Install app</b> or <b>Add to Home screen</b>.</p>';m.classList.add('show')}
async function doInstall(){if(appState.deferredInstall){appState.deferredInstall.prompt();await appState.deferredInstall.userChoice;appState.deferredInstall=null;$('#installModal')?.classList.remove('show')}else if(isIOS())alert('In Safari, tap Share → Add to Home Screen.')}
window.openInstall=openInstall;window.doInstall=doInstall;
window.addEventListener('DOMContentLoaded',()=>{$('#closeInstall')?.addEventListener('click',()=>$('#installModal').classList.remove('show'));$('#installNow')?.addEventListener('click',doInstall);$('#installModal')?.addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.classList.remove('show')})});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));}
function fmtTime(s){if(!isFinite(s))return'00:00.0';const m=Math.floor(s/60),r=s-m*60;return `${String(m).padStart(2,'0')}:${r.toFixed(1).padStart(4,'0')}`}
function humanBytes(n){if(!n)return'0 B';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},3000)}
function writeAscii(v,o,t){for(let i=0;i<t.length;i++)v.setUint8(o+i,t.charCodeAt(i))}
function interleaveChannels(channels,length){const ch=channels.length,out=new Float32Array(length*ch);let k=0;for(let i=0;i<length;i++)for(let c=0;c<ch;c++)out[k++]=channels[c][i]||0;return out}
function pcmToWav(channels,sampleRate){const ch=channels.length,length=Math.max(...channels.map(a=>a.length)),pcm=interleaveChannels(channels,length),out=new ArrayBuffer(44+pcm.length*2),v=new DataView(out);writeAscii(v,0,'RIFF');v.setUint32(4,36+pcm.length*2,true);writeAscii(v,8,'WAVE');writeAscii(v,12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);writeAscii(v,36,'data');v.setUint32(40,pcm.length*2,true);let off=44;for(const x of pcm){const s=Math.max(-1,Math.min(1,x));v.setInt16(off,s<0?s*32768:s*32767,true);off+=2}return new Blob([out],{type:'audio/wav'})}
function audioBufferToWav(buffer){const channels=[];for(let c=0;c<buffer.numberOfChannels;c++)channels.push(buffer.getChannelData(c));return pcmToWav(channels,buffer.sampleRate)}
function audioBufferToAiff(buffer){const ch=buffer.numberOfChannels,frames=buffer.length,bps=16,dataBytes=frames*ch*2,out=new ArrayBuffer(54+dataBytes),v=new DataView(out);writeAscii(v,0,'FORM');v.setUint32(4,46+dataBytes,false);writeAscii(v,8,'AIFF');writeAscii(v,12,'COMM');v.setUint32(16,18,false);v.setUint16(20,ch,false);v.setUint32(22,frames,false);v.setUint16(26,bps,false);
 // 80-bit extended sample rate for common rates. Default to 44100/48000 exact constants.
 const sr=buffer.sampleRate; const ext=sr===48000?[0x40,0x0e,0xbb,0x80,0,0,0,0,0,0]:[0x40,0x0e,0xac,0x44,0,0,0,0,0,0]; ext.forEach((b,i)=>v.setUint8(28+i,b));
 writeAscii(v,38,'SSND');v.setUint32(42,8+dataBytes,false);v.setUint32(46,0,false);v.setUint32(50,0,false);let off=54;for(let i=0;i<frames;i++)for(let c=0;c<ch;c++){const s=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));v.setInt16(off,s<0?s*32768:s*32767,false);off+=2}return new Blob([out],{type:'audio/aiff'})}
function drawWave(canvas,buffer,selStart=0,selEnd=buffer?.duration||1){if(!canvas||!buffer)return;const dpr=devicePixelRatio||1,w=Math.max(1,canvas.clientWidth),h=Math.max(1,canvas.clientHeight);canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#061021';c.fillRect(0,0,w,h);const data=buffer.getChannelData(0),step=Math.max(1,Math.floor(data.length/w));c.strokeStyle='#3aa7ff';c.lineWidth=1;c.beginPath();for(let x=0;x<w;x++){let min=1,max=-1,st=x*step;for(let j=0;j<step&&st+j<data.length;j++){const q=data[st+j];min=Math.min(min,q);max=Math.max(max,q)}c.moveTo(x,(1+min)*h/2);c.lineTo(x,(1+max)*h/2)}c.stroke();const sx=selStart/buffer.duration*w,ex=selEnd/buffer.duration*w;c.fillStyle='rgba(36,140,255,.12)';c.fillRect(sx,0,Math.max(1,ex-sx),h);c.strokeStyle='#7fd7ff';c.beginPath();c.moveTo(sx,0);c.lineTo(sx,h);c.moveTo(ex,0);c.lineTo(ex,h);c.stroke()}
function impulse(ctx,seconds=1.5,decay=2){const len=Math.max(1,Math.floor(ctx.sampleRate*seconds)),b=ctx.createBuffer(2,len,ctx.sampleRate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay)}return b}
async function renderAudio(buffer,o={}){const sr=buffer.sampleRate,start=Math.max(0,o.start||0),end=Math.min(buffer.duration,o.end??buffer.duration),srcDur=Math.max(.01,end-start),rate=Math.pow(2,(o.pitch||0)/12),tail=(o.reverb||o.echo)?2:0,outDur=srcDur/rate+tail,ctx=new OfflineAudioContext(Math.min(2,buffer.numberOfChannels),Math.ceil(outDur*sr),sr),src=ctx.createBufferSource();src.buffer=buffer;src.playbackRate.value=rate;let node=src;
 if(o.reverse){const rb=ctx.createBuffer(buffer.numberOfChannels,Math.floor(srcDur*sr),sr);const s0=Math.floor(start*sr),e0=Math.min(buffer.length,Math.floor(end*sr));for(let c=0;c<buffer.numberOfChannels;c++){const d=rb.getChannelData(c),a=buffer.getChannelData(c);for(let i=0;i<d.length;i++)d[i]=a[e0-1-i]||0}src.buffer=rb}
 const low=ctx.createBiquadFilter();low.type='lowshelf';low.frequency.value=180;low.gain.value=o.bass||0;node.connect(low);node=low;const hi=ctx.createBiquadFilter();hi.type='peaking';hi.frequency.value=3200;hi.Q.value=.8;hi.gain.value=o.clarity||0;node.connect(hi);node=hi;
 if((o.comp||0)>0){const cp=ctx.createDynamicsCompressor();cp.threshold.value=-12-(o.comp||0)*.2;cp.ratio.value=1+(o.comp||0)*.09;node.connect(cp);node=cp}
 const gain=ctx.createGain(),g=(o.gain??1);gain.gain.setValueAtTime(g,0);if(o.fadeIn>0){gain.gain.setValueAtTime(0,0);gain.gain.linearRampToValueAtTime(g,Math.min(o.fadeIn,outDur))}if(o.fadeOut>0){gain.gain.setValueAtTime(g,Math.max(0,outDur-o.fadeOut));gain.gain.linearRampToValueAtTime(0,outDur)}node.connect(gain);node=gain;node.connect(ctx.destination);
 if((o.reverb||0)>0){const con=ctx.createConvolver(),wet=ctx.createGain();con.buffer=impulse(ctx);wet.gain.value=(o.reverb||0)/100;node.connect(con);con.connect(wet);wet.connect(ctx.destination)}
 if((o.echo||0)>0){const del=ctx.createDelay(1),fb=ctx.createGain(),wet=ctx.createGain();del.delayTime.value=.16;fb.gain.value=Math.min(.75,(o.echo||0)/130);wet.gain.value=.7;node.connect(del);del.connect(wet);wet.connect(ctx.destination);del.connect(fb);fb.connect(del)}
 src.start(0,o.reverse?0:start,srcDur);let rendered=await ctx.startRendering();if(o.normalize){let peak=0;for(let c=0;c<rendered.numberOfChannels;c++){const d=rendered.getChannelData(c);for(let i=0;i<d.length;i++)peak=Math.max(peak,Math.abs(d[i]))}if(peak>0){const copy=new AudioBuffer({length:rendered.length,numberOfChannels:rendered.numberOfChannels,sampleRate:rendered.sampleRate});for(let c=0;c<copy.numberOfChannels;c++){const srcd=rendered.getChannelData(c),dst=copy.getChannelData(c),mul=Math.min(4,.98/peak);for(let i=0;i<dst.length;i++)dst[i]=srcd[i]*mul}rendered=copy}}return rendered}
function pickAudioMime(fmt){const map={m4a:['audio/mp4;codecs=mp4a.40.2','audio/mp4'],aac:['audio/aac'],ogg:['audio/ogg;codecs=opus','audio/ogg'],opus:['audio/webm;codecs=opus','audio/ogg;codecs=opus'],webm:['audio/webm;codecs=opus','audio/webm'],mp3:['audio/mpeg']};return (map[fmt]||[]).find(m=>window.MediaRecorder?.isTypeSupported?.(m))||''}
async function encodeAudioRealtime(buffer,fmt,setStatus=()=>{}){if(fmt==='wav')return audioBufferToWav(buffer);if(fmt==='aiff')return audioBufferToAiff(buffer);const mime=pickAudioMime(fmt);if(!mime)throw new Error(`${fmt.toUpperCase()} encoding is not provided by this browser. WAV and AIFF always work.`);const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),dest=ctx.createMediaStreamDestination(),src=ctx.createBufferSource();src.buffer=buffer;src.connect(dest);const rec=new MediaRecorder(dest.stream,{mimeType:mime}),chunks=[];return await new Promise((resolve,reject)=>{rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onerror=e=>reject(e.error||e);rec.onstop=()=>{ctx.close();resolve(new Blob(chunks,{type:mime}))};src.onended=()=>setTimeout(()=>rec.state==='recording'&&rec.stop(),120);setStatus(`Encoding ${fmt.toUpperCase()}… this takes about the clip length.`);rec.start(250);src.start()})}
function extForMime(mime,fallback='bin'){if(mime.includes('mp4'))return'm4a';if(mime.includes('mpeg'))return'mp3';if(mime.includes('ogg'))return'ogg';if(mime.includes('webm'))return'webm';if(mime.includes('wav'))return'wav';return fallback}
function refreshFormatSelect(select){if(!select)return;[...select.options].forEach(o=>{if(['wav','aiff','original'].includes(o.value))return;const ok=!!pickAudioMime(o.value);o.disabled=!ok;if(!ok&&!o.text.includes('not supported'))o.text+=' — not supported on this device'});if(select.selectedOptions[0]?.disabled)select.value='wav'}
function concatFloat32(parts){let n=0;for(const p of parts)n+=p.length;const out=new Float32Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function fileExt(name=''){return name.split('.').pop()?.toLowerCase()||''}
window.addEventListener('DOMContentLoaded',()=>{refreshFormatSelect($('#exportFormat'));refreshFormatSelect($('#format'));refreshFormatSelect($('#voiceFormat'))});
window.Blue={$, $$,fmtTime,humanBytes,downloadBlob,pcmToWav,audioBufferToWav,audioBufferToAiff,drawWave,renderAudio,encodeAudioRealtime,pickAudioMime,extForMime,refreshFormatSelect,concatFloat32,fileExt,isIOS};
