const{$,fmtTime,humanBytes,downloadBlob,pcmToWav,extForMime,concatFloat32,encodeAudioRealtime}=Blue;
let stream=null,ctx=null,source=null,analyser=null,processor=null,nativeRecorder=null,nativeChunks=[],pcmChunks=[],sampleRate=44100,startedAt=0,timerId=0,raf=0,recording=false,nativeBlob=null,wavBlob=null,audioBuffer=null,previewURL=null;
const meter=$('#meter');for(let i=0;i<48;i++){const b=document.createElement('i');b.className='bar';meter.appendChild(b)}const bars=[...meter.children];
const setStatus=t=>$('#recStatus').textContent=t;
function secureCheck(){if(!window.isSecureContext){setStatus('Microphone access requires HTTPS. Publish through GitHub Pages (https://) rather than opening the HTML file directly.');return false}if(!navigator.mediaDevices?.getUserMedia){setStatus('This browser does not expose microphone access. Use Safari/Chrome/Edge over HTTPS.');return false}return true}
async function refreshDevices(){if(!navigator.mediaDevices?.enumerateDevices)return;const devices=(await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='audioinput'),sel=$('#micDevice');if(!sel)return;const old=sel.value;sel.innerHTML='';devices.forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`Microphone ${i+1}`;sel.appendChild(o)});if(old&&[...sel.options].some(o=>o.value===old))sel.value=old;$('#micCount').textContent=`${devices.length} input${devices.length===1?'':'s'} detected`}
function meterLoop(){if(!analyser)return;const d=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(d);let sum=0;bars.forEach((b,i)=>{const v=d[Math.floor(i*d.length/bars.length)]||0;sum+=v;b.style.height=`${8+(v/255)*72}px`});$('#liveLevel').textContent=`${Math.round(sum/bars.length/255*100)}%`;raf=requestAnimationFrame(meterLoop)}
function bestNativeMime(){return ['audio/mp4;codecs=mp4a.40.2','audio/mp4','audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus'].find(m=>window.MediaRecorder?.isTypeSupported?.(m))||''}
async function enableMic(){if(!secureCheck())return false;try{stopTracks();const deviceId=$('#micDevice')?.value;stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:deviceId?{exact:deviceId}:undefined,channelCount:{$ideal:1},echoCancellation:$('#echoCancel')?.checked!==false,noiseSuppression:$('#noiseSuppress')?.checked!==false,autoGainControl:$('#autoGain')?.checked!==false}});const C=window.AudioContext||window.webkitAudioContext;ctx=new C();await ctx.resume();sampleRate=ctx.sampleRate;source=ctx.createMediaStreamSource(stream);analyser=ctx.createAnalyser();analyser.fftSize=256;source.connect(analyser);meterLoop();await refreshDevices();$('#micState').textContent='Live microphone';$('#micState').classList.add('live');$('#recordBtn').disabled=false;setStatus('Microphone is live. The level meter above is reading your real mic. Tap Record when ready.');return true}catch(e){setStatus(`Microphone permission failed: ${e.message||e.name}. Check Settings → Safari/Chrome → Microphone.`);$('#micState').textContent='Mic blocked';return false}}
function stopTracks(){cancelAnimationFrame(raf);if(processor){try{processor.disconnect()}catch{}processor=null}if(source){try{source.disconnect()}catch{}source=null}stream?.getTracks().forEach(t=>t.stop());stream=null;if(ctx){ctx.close().catch(()=>{});ctx=null}bars.forEach(b=>b.style.height='8px');$('#liveLevel').textContent='0%'}
async function startRecording(){if(recording)return;if(!stream||!ctx){const ok=await enableMic();if(!ok)return}pcmChunks=[];nativeChunks=[];nativeBlob=null;wavBlob=null;processor=ctx.createScriptProcessor(4096,1,1);source.connect(processor);const mute=ctx.createGain();mute.gain.value=0;processor.connect(mute);mute.connect(ctx.destination);processor.onaudioprocess=e=>{if(!recording)return;pcmChunks.push(new Float32Array(e.inputBuffer.getChannelData(0)))};
 const mime=bestNativeMime();if(window.MediaRecorder){try{nativeRecorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);nativeRecorder.ondataavailable=e=>e.data.size&&nativeChunks.push(e.data);nativeRecorder.start(250);$('#recFormat').textContent=mime||'Browser native'}catch{nativeRecorder=null}}
 recording=true;startedAt=performance.now();$('#recordBtn').classList.add('recording');$('#recordBtn').setAttribute('aria-label','Stop recording');setStatus('Recording from the live microphone…');timerId=setInterval(()=>$('#timer').textContent=fmtTime((performance.now()-startedAt)/1000),100)}
async function stopRecording(){if(!recording)return;recording=false;clearInterval(timerId);$('#recordBtn').classList.remove('recording');if(nativeRecorder&&nativeRecorder.state!=='inactive'){await new Promise(r=>{nativeRecorder.addEventListener('stop',r,{once:true});nativeRecorder.stop()})}if(processor){try{processor.disconnect()}catch{}processor=null}const pcm=concatFloat32(pcmChunks);wavBlob=pcmToWav([pcm],sampleRate);audioBuffer=ctx.createBuffer(1,pcm.length,sampleRate);audioBuffer.copyToChannel(pcm,0);if(nativeChunks.length)nativeBlob=new Blob(nativeChunks,{type:nativeRecorder?.mimeType||nativeChunks[0]?.type||'audio/webm'});const dur=pcm.length/sampleRate;$('#timer').textContent=fmtTime(dur);$('#durationStat').textContent=`${dur.toFixed(1)}s`;$('#sizeStat').textContent=humanBytes(wavBlob.size);if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(wavBlob);const a=$('#preview');a.src=previewURL;a.style.display='block';['#playBtn','#wavBtn','#clearBtn','#convertBtn'].forEach(id=>$(id).disabled=false);$('#downloadNative').disabled=!nativeBlob;setStatus(`Recording complete • ${sampleRate} Hz PCM captured from the microphone.`)}
$('#enableMic').onclick=enableMic;$('#micDevice').onchange=enableMic;$('#recordBtn').onclick=()=>recording?stopRecording():startRecording();$('#playBtn').onclick=async()=>{const a=$('#preview');if(a.paused){try{await a.play()}catch{setStatus('Playback was blocked. Tap Preview again.')}}else a.pause()};$('#wavBtn').onclick=()=>wavBlob&&downloadBlob(wavBlob,`mic-recording-${Date.now()}.wav`);$('#downloadNative').onclick=()=>nativeBlob&&downloadBlob(nativeBlob,`mic-recording-${Date.now()}.${extForMime(nativeBlob.type,'m4a')}`);$('#clearBtn').onclick=()=>{if(recording)stopRecording();nativeBlob=wavBlob=audioBuffer=null;pcmChunks=[];const a=$('#preview');a.pause();a.removeAttribute('src');a.load();a.style.display='none';$('#timer').textContent='00:00.0';$('#durationStat').textContent='0.0s';$('#sizeStat').textContent='0 B';['#playBtn','#wavBtn','#downloadNative','#clearBtn','#convertBtn'].forEach(id=>$(id).disabled=true);setStatus(stream?'Microphone is live. Tap Record when ready.':'Enable your microphone to start.')};
window.addEventListener('pagehide',stopTracks);navigator.mediaDevices?.addEventListener?.('devicechange',refreshDevices);refreshDevices();

$('#convertBtn').onclick=async()=>{if(!audioBuffer)return;const fmt=$('#exportFormat').value,status=$('#convertStatus');try{status.textContent=`Encoding ${fmt.toUpperCase()}…`;const out=await encodeAudioRealtime(audioBuffer,fmt,t=>status.textContent=t);downloadBlob(out,`mic-recording-${Date.now()}.${fmt}`);status.textContent=`${fmt.toUpperCase()} export complete.`}catch(e){status.textContent=e.message||'Export failed.'}};
