const{$,downloadBlob,humanBytes,pcmToWav,concatFloat32,fileExt}=Blue;let file,videoURL,audioCtx,audioSource;const drop=$('#vDrop');
['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>load(e.dataTransfer.files[0]));$('#vFile').onchange=e=>load(e.target.files[0]);
function load(f){if(!f)return;file=f;if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(f);const v=$('#video');v.src=videoURL;v.style.display='block';drop.style.display='none';$('#vReplace').style.display='inline-flex';$('#vMeta').textContent=`${f.name} • ${humanBytes(f.size)}`;$('#vStatus').textContent='Loading real media file…';v.onloadedmetadata=()=>{const d=isFinite(v.duration)?v.duration:0;$('#vEnd').value=d.toFixed(2);$('#vExport').disabled=false;$('#extractWav').disabled=false;$('#frameBtn').disabled=false;$('#vStatus').textContent=`Loaded • ${d.toFixed(2)}s • ${v.videoWidth||0}×${v.videoHeight||0}`};v.onerror=()=>$('#vStatus').textContent=`The file was selected, but this browser cannot decode ${fileExt(f.name).toUpperCase()||'that'} video codec. MP4/H.264 and MOV are most reliable on iPhone.`}
$('#vReplace').onclick=()=>$('#vFile').click();
function pickVideoMime(fmt){const map={mp4:['video/mp4;codecs="avc1.42E01E,mp4a.40.2"','video/mp4'],webm:['video/webm;codecs=vp8,opus','video/webm;codecs=vp9,opus','video/webm']};return (map[fmt]||[]).find(m=>window.MediaRecorder?.isTypeSupported?.(m))||''}
async function seek(v,t){if(Math.abs(v.currentTime-t)<.03)return;await new Promise((res,rej)=>{let done=false;const finish=()=>{if(done)return;done=true;v.removeEventListener('seeked',finish);res()};v.addEventListener('seeked',finish,{once:true});v.currentTime=t;setTimeout(finish,1500)})}
async function prepareAudioGraph(){const v=$('#video');if(audioSource)return;const C=window.AudioContext||window.webkitAudioContext;audioCtx=new C();await audioCtx.resume();audioSource=audioCtx.createMediaElementSource(v);audioSource.connect(audioCtx.destination)}
async function renderTrim(fmt,start,end){const v=$('#video'),mime=pickVideoMime(fmt);if(!window.MediaRecorder)throw new Error('MediaRecorder is unavailable on this browser.');if(!mime)throw new Error(`${fmt.toUpperCase()} encoding is not available on this device. Try the other video format.`);if(!HTMLCanvasElement.prototype.captureStream)throw new Error('This browser cannot render a new video stream from canvas.');await prepareAudioGraph();await seek(v,start);v.pause();
 const canvas=document.createElement('canvas');canvas.width=v.videoWidth||1280;canvas.height=v.videoHeight||720;const c=canvas.getContext('2d',{alpha:false});const fps=30,canvasStream=canvas.captureStream(fps),dest=audioCtx.createMediaStreamDestination();audioSource.connect(dest);const tracks=[...canvasStream.getVideoTracks(),...dest.stream.getAudioTracks()];const outStream=new MediaStream(tracks),rec=new MediaRecorder(outStream,{mimeType:mime,videoBitsPerSecond:8000000,audioBitsPerSecond:192000}),chunks=[];
 const total=end-start;let rafId;return await new Promise(async(resolve,reject)=>{rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onerror=e=>reject(e.error||e);rec.onstop=()=>{cancelAnimationFrame(rafId);try{audioSource.disconnect(dest)}catch{}resolve(new Blob(chunks,{type:mime}))};const draw=()=>{try{c.drawImage(v,0,0,canvas.width,canvas.height)}catch{}const p=Math.max(0,Math.min(1,(v.currentTime-start)/total));$('#vProgress').value=p*100;$('#vProgressText').textContent=`${Math.round(p*100)}%`;if(v.currentTime>=end||v.ended){v.pause();if(rec.state==='recording')rec.stop();return}rafId=requestAnimationFrame(draw)};rec.start(250);try{await v.play()}catch(e){rec.stop();reject(new Error('Playback permission blocked the render. Tap the video once, then export again.'));return}draw()})}
async function extractWav(start,end){const v=$('#video');await prepareAudioGraph();await seek(v,start);v.pause();const processor=audioCtx.createScriptProcessor(4096,2,2),silent=audioCtx.createGain();silent.gain.value=0;audioSource.connect(processor);processor.connect(silent);silent.connect(audioCtx.destination);const left=[],right=[];processor.onaudioprocess=e=>{left.push(new Float32Array(e.inputBuffer.getChannelData(0)));if(e.inputBuffer.numberOfChannels>1)right.push(new Float32Array(e.inputBuffer.getChannelData(1)))};return await new Promise(async(resolve,reject)=>{const total=end-start;const watch=()=>{const p=Math.max(0,Math.min(1,(v.currentTime-start)/total));$('#vProgress').value=p*100;$('#vProgressText').textContent=`${Math.round(p*100)}%`;if(v.currentTime>=end||v.ended){v.pause();processor.onaudioprocess=null;try{audioSource.disconnect(processor);processor.disconnect();silent.disconnect()}catch{}const channels=[concatFloat32(left)];if(right.length)channels.push(concatFloat32(right));resolve(pcmToWav(channels,audioCtx.sampleRate));return}requestAnimationFrame(watch)};try{await v.play();watch()}catch(e){reject(new Error('Playback permission blocked audio extraction. Tap the video once and retry.'))}})}
function times(){const v=$('#video'),start=Math.max(0,+$('#vStart').value||0),end=Math.min(v.duration||Infinity,+$('#vEnd').value||v.duration||0);if(end<=start)throw new Error('End time must be after start time.');return{start,end}}
$('#vExport').onclick=async()=>{if(!file)return;const fmt=$('#vFormat').value,status=$('#vStatus');try{const{start,end}=times();if(fmt==='original'){downloadBlob(file,file.name);status.textContent='Original file downloaded.';return}status.textContent=`Rendering a real ${fmt.toUpperCase()} from ${start.toFixed(1)}s to ${end.toFixed(1)}s… keep this page open.`;$('#vProgressWrap').style.display='block';const out=await renderTrim(fmt,start,end);downloadBlob(out,`${file.name.replace(/\.[^.]+$/,'')}-trimmed.${fmt}`);status.textContent=`Video export complete • ${humanBytes(out.size)}.`}catch(e){console.error(e);status.textContent=e.message||'Video export failed.'}};
$('#extractWav').onclick=async()=>{if(!file)return;const status=$('#vStatus');try{const{start,end}=times();status.textContent='Extracting real audio from the selected video…';$('#vProgressWrap').style.display='block';const out=await extractWav(start,end);downloadBlob(out,`${file.name.replace(/\.[^.]+$/,'')}-audio.wav`);status.textContent=`Extracted WAV audio • ${humanBytes(out.size)}.`}catch(e){status.textContent=e.message||'Audio extraction failed.'}};
$('#frameBtn').onclick=async()=>{const v=$('#video');if(!file)return;const canvas=document.createElement('canvas');canvas.width=v.videoWidth;canvas.height=v.videoHeight;canvas.getContext('2d').drawImage(v,0,0);canvas.toBlob(b=>b&&downloadBlob(b,`${file.name.replace(/\.[^.]+$/,'')}-frame.png`),'image/png')};
